# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'ArrkDemoApp' do
  use_frameworks!

  pod 'Alamofire', '~> 4.4’
  pod 'SwiftyJSON'
  pod 'AlamofireImage'
  pod 'JGProgressHUD'

	target 'ArrkDemoAppTests' do
	    inherit! :search_paths
	    # Pods for testing
		pod 'Alamofire', '~> 4.4’
		pod 'SwiftyJSON'
		pod 'AlamofireImage'
		pod 'JGProgressHUD'
	end

end
